### ISSUE TITLE
能不能别用百度盘。

### ISSUE THREAD

**Issue by charley008** [Chernfalin/SuperRimeDict#1]
非要下载百度客户端才能下。蓝奏或者天翼云啥的都可以啊

**Comment by charley008** [comment]
还有windows10 20h2 无法导入

**Comment by PDxtXHd** [comment]
伸手党还这么理直气壮真好笑啊:smile:

**Comment by nanbowaner** [comment]
Super Rime拓展词库 For Win 10拼音版( 600万词 含 Better Rime) V 20.3
https://archive.org/details/super-rime-for-win-10-600-better-rime-v-20.3
